import { z } from "zod";

export const UnitIdSchema = z.string().min(1).brand<"UnitId">();
export const ClassIdSchema = z.string().min(1).brand<"ClassId">();
export const WeaponIdSchema = z.string().min(1).brand<"WeaponId">();
export const ItemIdSchema = z.string().min(1).brand<"ItemId">();
export const SkillIdSchema = z.string().min(1).brand<"SkillId">();
export const TerrainIdSchema = z.string().min(1).brand<"TerrainId">();
export const MapIdSchema = z.string().min(1).brand<"MapId">();
export const EventIdSchema = z.string().min(1).brand<"EventId">();
export const VariableIdSchema = z.string().min(1).brand<"VariableId">();
export const SwitchIdSchema = z.string().min(1).brand<"SwitchId">();
export const ChapterIdSchema = z.string().min(1).brand<"ChapterId">();
export const BgmIdSchema = z.string().min(1).brand<"BgmId">();
export const SeIdSchema = z.string().min(1).brand<"SeId">();
export const FaceIdSchema = z.string().min(1).brand<"FaceId">();

export type UnitId = z.infer<typeof UnitIdSchema>;
export type ClassId = z.infer<typeof ClassIdSchema>;
export type WeaponId = z.infer<typeof WeaponIdSchema>;
export type ItemId = z.infer<typeof ItemIdSchema>;
export type SkillId = z.infer<typeof SkillIdSchema>;
export type TerrainId = z.infer<typeof TerrainIdSchema>;
export type MapId = z.infer<typeof MapIdSchema>;
export type EventId = z.infer<typeof EventIdSchema>;
export type VariableId = z.infer<typeof VariableIdSchema>;
export type SwitchId = z.infer<typeof SwitchIdSchema>;
export type ChapterId = z.infer<typeof ChapterIdSchema>;
export type BgmId = z.infer<typeof BgmIdSchema>;
export type SeId = z.infer<typeof SeIdSchema>;
export type FaceId = z.infer<typeof FaceIdSchema>;
